import { SchemaField } from "@/types/schema.types";

export const footerSchemaFields: SchemaField[] = [
    { key: 'footer_brand_badge_text', label: 'Brand Badge Text', type: 'text', default: 'P' },
    { key: 'footer_brand_name', label: 'Brand Name', type: 'text', default: 'Dogs Paradise' },
    { key: 'footer_tagline', label: 'Footer Tagline', type: 'textarea', default: 'Health details are shared clearly for every puppy, with breeder support before and after pickup.' },
    { key: 'footer_phone', label: 'Footer Phone', type: 'text', default: '+91 98765 43210' },
    { key: 'footer_email', label: 'Footer Email', type: 'text', default: 'hello@dogsparadise.in' },
    { key: 'footer_address', label: 'Footer Address', type: 'text', default: 'Main Road, Whitefield' },
    { key: 'footer_city', label: 'Footer City', type: 'text', default: 'Bangalore' },

    { key: 'quick_link_1_label', label: 'Quick Link 1 Label', type: 'text', default: 'All Breeds' },
    { key: 'quick_link_1_url', label: 'Quick Link 1 URL', type: 'text', default: '/breeds' },
    { key: 'quick_link_2_label', label: 'Quick Link 2 Label', type: 'text', default: 'Available Puppies' },
    { key: 'quick_link_2_url', label: 'Quick Link 2 URL', type: 'text', default: '/breeds?status=available' },
    { key: 'quick_link_3_label', label: 'Quick Link 3 Label', type: 'text', default: 'Happy Customers' },
    { key: 'quick_link_3_url', label: 'Quick Link 3 URL', type: 'text', default: '/happy-customers' },
    { key: 'quick_link_4_label', label: 'Quick Link 4 Label', type: 'text', default: 'About Us' },
    { key: 'quick_link_4_url', label: 'Quick Link 4 URL', type: 'text', default: '/about' },
    { key: 'quick_link_5_label', label: 'Quick Link 5 Label', type: 'text', default: 'Blog' },
    { key: 'quick_link_5_url', label: 'Quick Link 5 URL', type: 'text', default: '/blog' },
    { key: 'quick_link_6_label', label: 'Quick Link 6 Label', type: 'text', default: 'Contact' },
    { key: 'quick_link_6_url', label: 'Quick Link 6 URL', type: 'text', default: '/contact' },

    { key: 'breed_link_1_label', label: 'Breed Link 1 Label', type: 'text', default: 'Golden Retriever' },
    { key: 'breed_link_1_url', label: 'Breed Link 1 URL', type: 'text', default: '/breeds/golden-retriever' },
    { key: 'breed_link_2_label', label: 'Breed Link 2 Label', type: 'text', default: 'Labrador Retriever' },
    { key: 'breed_link_2_url', label: 'Breed Link 2 URL', type: 'text', default: '/breeds/labrador-retriever' },
    { key: 'breed_link_3_label', label: 'Breed Link 3 Label', type: 'text', default: 'German Shepherd' },
    { key: 'breed_link_3_url', label: 'Breed Link 3 URL', type: 'text', default: '/breeds/german-shepherd' },
    { key: 'breed_link_4_label', label: 'Breed Link 4 Label', type: 'text', default: 'Siberian Husky' },
    { key: 'breed_link_4_url', label: 'Breed Link 4 URL', type: 'text', default: '/breeds/siberian-husky' },
    { key: 'breed_link_5_label', label: 'Breed Link 5 Label', type: 'text', default: 'French Bulldog' },
    { key: 'breed_link_5_url', label: 'Breed Link 5 URL', type: 'text', default: '/breeds/french-bulldog' },
    { key: 'breed_link_6_label', label: 'Breed Link 6 Label', type: 'text', default: 'Rottweiler' },
    { key: 'breed_link_6_url', label: 'Breed Link 6 URL', type: 'text', default: '/breeds/rottweiler' },

    { key: 'promise_item_1', label: 'Promise Item 1', type: 'text', default: 'Select KCI Registration Options' },
    { key: 'promise_item_2', label: 'Promise Item 2', type: 'text', default: 'Age-Appropriate Vaccination' },
    { key: 'promise_item_3', label: 'Promise Item 3', type: 'text', default: 'Vet Health Checks' },
    { key: 'promise_item_4', label: 'Promise Item 4', type: 'text', default: 'Home-Raised Puppies' },
    { key: 'promise_item_5', label: 'Promise Item 5', type: 'text', default: 'Lifetime Breeder Support' },
    { key: 'promise_item_6', label: 'Promise Item 6', type: 'text', default: 'Clear Health Guidance' },

    { key: 'footer_copyright_text', label: 'Copyright Text', type: 'text', default: '© 2026 Dogs Paradise. All rights reserved.' },
    { key: 'footer_made_with_text', label: 'Made With Text', type: 'text', default: 'Made with love in Bangalore' },
    { key: 'footer_bg_color', label: 'Footer Background', type: 'color', default: '#ffffff' },
    { key: 'footer_border_color', label: 'Footer Border Color', type: 'color', default: '#e5e7eb' },
];
