import { SchemaField } from "@/types/schema.types";

export const headerSchemaFields: SchemaField[] = [
    { key: 'mobile_menu_title', label: 'Mobile Menu Title', type: 'text', group: 'Content', default: '', placeholder: 'Optional menu title' },
    { key: 'sticky_header', label: 'Sticky Header', type: 'toggle', group: 'Design', default: true },
    { key: 'header_shadow_enabled', label: 'Show Header Shadow', type: 'toggle', group: 'Design', default: true },
    { key: 'header_bg_transparent', label: 'Glass Header Effect', type: 'toggle', group: 'Design', default: false },
    { key: 'header_bg_color', label: 'Header Background', type: 'color', group: 'Design' },
    { key: 'header_border_color', label: 'Header Border Color', type: 'color', group: 'Design' },
    { key: 'header_text_color', label: 'Header Text Color', type: 'color', group: 'Design' },
    {
        key: 'enable_global_section_bg',
        label: 'Use One Background For All Homepage Sections',
        type: 'toggle',
        group: 'Content',
        default: false,
    },
    {
        key: 'global_section_bg_color',
        label: 'Global Sections Background (Color / Gradient)',
        type: 'color',
        group: 'Content',
        placeholder: 'e.g. #302b63 or linear-gradient(...)',
    },
    {
        key: 'body_bg_color',
        label: 'Website Body Background (Color / Gradient)',
        type: 'color',
        group: 'Content',
        placeholder: 'e.g. #302b63 or linear-gradient(...)',
    },
    {
        key: 'global_visual_preset',
        label: 'Website Visual Preset',
        type: 'select',
        options: ['custom', 'black-gold-dust-soft', 'black-gold-dust-rich'],
        group: 'Content',
        default: 'custom',
    },
    {
        key: 'enable_gold_dust_overlay',
        label: 'Show Rising Golden Dust Overlay',
        type: 'toggle',
        group: 'Content',
        default: false,
    },
    {
        key: 'gold_dust_density',
        label: 'Golden Dust Density',
        type: 'range',
        group: 'Content',
        default: 0.45,
        min: 0.1,
        max: 1,
        step: 0.05,
    },
    {
        key: 'gold_dust_speed',
        label: 'Golden Dust Speed',
        type: 'range',
        group: 'Content',
        default: 1,
        min: 0.6,
        max: 2,
        step: 0.05,
    },
    {
        key: 'gold_dust_size',
        label: 'Golden Dust Size',
        type: 'range',
        group: 'Content',
        default: 1,
        min: 0.6,
        max: 1.8,
        step: 0.05,
    },
    {
        key: 'gold_dust_opacity',
        label: 'Golden Dust Opacity',
        type: 'range',
        group: 'Content',
        default: 0.45,
        min: 0.1,
        max: 1,
        step: 0.05,
    },
    {
        key: 'gold_dust_color',
        label: 'Golden Dust Color',
        type: 'color',
        group: 'Content',
        default: '#d4af37',
        placeholder: 'e.g. #d4af37',
    },
    { key: 'logo_size', label: 'Logo Size (px)', type: 'range', group: 'Design', default: 40, min: 24, max: 160, step: 1 },
    { key: 'brand_text_size', label: 'Brand Text Size (px)', type: 'range', group: 'Design', default: 24, min: 14, max: 42, step: 1 },
    { key: 'brand_font_weight', label: 'Brand Font Weight', type: 'select', options: ['normal', 'medium', 'semibold', 'bold'], group: 'Design', default: 'bold' },
    { key: 'nav_text_size', label: 'Navigation Text Size (px)', type: 'range', group: 'Design', default: 15, min: 12, max: 24, step: 1 },
    { key: 'nav_alignment', label: 'Navigation Alignment', type: 'select', options: ['left', 'center', 'right'], group: 'Design', default: 'right' },
    { key: 'nav_weight', label: 'Navigation Font Weight', type: 'select', options: ['normal', 'medium', 'semibold', 'bold'], group: 'Design', default: 'medium' },
    { key: 'nav_text_transform', label: 'Navigation Text Transform', type: 'select', options: ['none', 'uppercase', 'capitalize'], group: 'Design', default: 'none' },
    { key: 'nav_letter_spacing', label: 'Navigation Letter Spacing (em)', type: 'range', group: 'Design', default: 0, min: -0.05, max: 0.2, step: 0.01 },
    { key: 'desktop_padding_y', label: 'Desktop Vertical Padding', type: 'select', options: ['compact', 'default', 'spacious'], group: 'Design', default: 'default' },
    { key: 'mobile_padding_y', label: 'Mobile Vertical Padding', type: 'select', options: ['compact', 'default', 'spacious'], group: 'Design', default: 'default' },
    { key: 'mobile_menu_icon', label: 'Mobile Menu Icon', type: 'select', options: ['hamburger', 'three-dot'], group: 'Content', default: 'three-dot' },
    { key: 'mobile_menu_mode', label: 'Mobile Menu Open Style', type: 'select', options: ['dropdown', 'left-drawer', 'right-drawer', 'front-panel'], group: 'Content', default: 'left-drawer' },
    { key: 'mobile_menu_subtitle', label: 'Mobile Menu Subtitle', type: 'text', group: 'Content', placeholder: 'Optional subtitle under menu title' },
    { key: 'mobile_menu_primary_cta_text', label: 'Mobile Primary Button Text', type: 'text', group: 'Content', placeholder: 'e.g. Browse Puppies' },
    { key: 'mobile_menu_primary_cta_url', label: 'Mobile Primary Button URL', type: 'text', group: 'Content', placeholder: '/breeds' },
    { key: 'mobile_menu_whatsapp_url', label: 'Mobile WhatsApp URL', type: 'text', group: 'Content', placeholder: 'https://wa.me/...' },
    { key: 'mobile_menu_instagram_url', label: 'Mobile Instagram URL', type: 'text', group: 'Content', placeholder: 'https://instagram.com/...' },
    { key: 'mobile_menu_youtube_url', label: 'Mobile YouTube URL', type: 'text', group: 'Content', placeholder: 'https://youtube.com/...' },
    { key: 'mobile_menu_width', label: 'Mobile Menu Width (px)', type: 'range', group: 'Design', default: 340, min: 220, max: 420, step: 2 },
    { key: 'mobile_menu_radius', label: 'Mobile Menu Radius (px)', type: 'range', group: 'Design', default: 0, min: 0, max: 36, step: 1 },
    { key: 'mobile_menu_bg_color', label: 'Mobile Menu Background', type: 'color', group: 'Design', default: '#050505' },
    { key: 'mobile_menu_text_color', label: 'Mobile Menu Text Color', type: 'color', group: 'Design', default: '#f8fafc' },
    { key: 'mobile_menu_enable_active_highlight', label: 'Highlight Active Mobile Menu Item', type: 'toggle', group: 'Design', default: true },
    { key: 'mobile_menu_active_bg_color', label: 'Mobile Active Card Background', type: 'color', group: 'Design', default: '#f97316' },
    { key: 'mobile_menu_active_text_color', label: 'Mobile Active Card Text Color', type: 'color', group: 'Design', default: '#ffffff' },
    { key: 'mobile_menu_card_bg_color', label: 'Mobile Card Background', type: 'color', group: 'Design', default: 'rgba(255,255,255,0.05)' },
    { key: 'mobile_menu_card_border_color', label: 'Mobile Card Border Color', type: 'color', group: 'Design', default: 'rgba(255,255,255,0.16)' },
    { key: 'mobile_menu_icon_bg_color', label: 'Mobile Icon Background', type: 'color', group: 'Design', default: '#060f2b' },
    { key: 'mobile_menu_icon_color', label: 'Mobile Icon Color', type: 'color', group: 'Design', default: '#8f9bb3' },
    { key: 'mobile_menu_icon_active_bg_color', label: 'Mobile Active Icon Background', type: 'color', group: 'Design', default: '#f7944d' },
    { key: 'mobile_menu_icon_active_color', label: 'Mobile Active Icon Color', type: 'color', group: 'Design', default: '#ffffff' },
    { key: 'mobile_menu_backdrop_enabled', label: 'Show Mobile Menu Backdrop', type: 'toggle', group: 'Design', default: true },
    { key: 'mobile_menu_backdrop_color', label: 'Mobile Backdrop Color', type: 'color', group: 'Design', default: '#0f172a' },
    { key: 'mobile_menu_backdrop_opacity', label: 'Mobile Backdrop Opacity', type: 'range', group: 'Design', default: 0.45, min: 0, max: 0.9, step: 0.05 },
];
